In [1]:
import tensorflow as tf
import numpy as np

2024-08-25 16:10:00.526726: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-25 16:10:00.663333: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-25 16:10:00.704941: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-25 16:10:00.944162: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-25 16:10:02.858493: W tensorflow/compiler/tf2

In [12]:
a = tf.constant([[1,2,3,4]], dtype=tf.int32)
tf.transpose(a) @ a

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]], dtype=int32)>

In [16]:
tf.concat([a,a,a], axis=-1)

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]], dtype=int32)>

In [21]:
v = tf.Variable(a)
v.assign_add(a)

<tf.Variable 'UnreadVariable' shape=(1, 4) dtype=int32, numpy=array([[2, 4, 6, 8]], dtype=int32)>

In [12]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [23]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

# everytime shape or dtype of x changes, a new graph is generated

In [27]:
my_func(tf.constant([1,2]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [29]:
tf.saved_model.save(my_func, 'myfunc') 
# only work with objects of subclasses of tf.Module, like keras.Model or keras.layers.Layer
# @tf. functions should only contain tf ops, and avoid python ops

In [32]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

tf.ragged.constant(ragged_list)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

In [33]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [35]:
tf.strings.split(tensor_of_strings).shape

TensorShape([3, None])

In [43]:
text = tf.constant("1 10 100")
text

<tf.Tensor: shape=(), dtype=string, numpy=b'1 10 100'>

In [44]:
tf.strings.to_number(tf.strings.split(text, " "))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  10., 100.], dtype=float32)>

In [47]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)
